name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/modern_programming_technologies/my-app:test .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/modern_programming_technologies/my-app:test

      - name: Run Docker container
        run: docker run --name my-app-container ghcr.io/${{ github.repository_owner }}/modern_programming_technologies/my-app:test pytest test_sorting.py


      - name: Create test-results directory
        run: mkdir -p test-results/

      - name: Copy test results from container
        run: docker cp my-app-container:/app/test-results/ ./test-results/

      - name: Checkout test-results branch or create it
        run: |
          git fetch
          if git show-ref --verify --quiet "refs/heads/test-results"; then
            git checkout test-results
          else
            git checkout --orphan test-results
            git config --global user.email "exiukaiwhooo@gmail.com"
            git config --global user.name "Anastasia"
            git reset --hard
            git commit --allow-empty -m "Initial empty commit"
          fi
      - name: Add and commit test results
        run: |
          if [ -d "test-results/" ] && [ "$(ls -A test-results/)" ]; then
            git add test-results/*
            git commit -m "Update test results"
            git push -u origin test-results --force
          else
            echo "No test results to commit."
          fi


