name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: docker build -t my-app:test .

      - name: Run Docker container
        run: docker run --name my-app-container my-app:test

      - name: Create test-results directory
        run: mkdir -p test-results/

      - name: Copy test results from container
        run: docker cp my-app-container:/app/test-results/ ./test-results/

      - name: Checkout test-results branch or create it
         run: |
          git fetch
          if git show-ref --verify --quiet "refs/heads/test-results"; then
            git checkout test-results
          else
            git checkout --orphan test-results
            git config --global user.email "exiukaiwhooo@gmail.com"
            git config --global user.name "Anastasia"
            git reset --hard
            git commit --allow-empty -m "Initial empty commit"
          fi
       - name: Add and commit test results
        run: |
          if [ -d "test-results/" ] && [ "$(ls -A test-results/)" ]; then
            git add test-results/*
            git commit -m "Update test results"
            git push -u origin test-results --force
          else
            echo "No test results to commit."
          fi

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zikozikoni/workflows:latest

